version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: task_manager_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mongodb:
    image: mongo:6
    container_name: task_manager_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: task_manager
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  web:
    build: .
    container_name: task_manager_web
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongodb
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
      - REDIS_URL=redis://redis:6379/0
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DB=task_manager
      - SECRET_KEY=your-very-secret-docker-key-change-in-production
      - DEBUG=True
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped

  celery:
    build: .
    container_name: task_manager_celery
    depends_on:
      - redis
      - mongodb
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
      - REDIS_URL=redis://redis:6379/0
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DB=task_manager
      - SECRET_KEY=your-very-secret-docker-key-change-in-production
    volumes:
      - .:/app
    command: celery -A project worker --loglevel=info
    restart: unless-stopped

volumes:
  redis_data:
  mongodb_data:
